// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TransferItem } from "./types.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type InventoryInteractSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "evefrontier", name: "InventoryInterac" }))
InventoryInteractSystemType constant inventoryInteractSystem = InventoryInteractSystemType.wrap(
  0x737965766566726f6e74696572000000496e76656e746f7279496e7465726163
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title InventoryInteractSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library InventoryInteractSystemLib {
  error InventoryInteractSystemLib_CallingFromRootSystem();
  error Inventory_InvalidTransferItemQuantity(
    string message,
    uint256 smartObjectId,
    string inventoryType,
    address inventoryOwner,
    uint256 inventoryItemId,
    uint256 quantity
  );

  function ephemeralToInventoryTransfer(
    InventoryInteractSystemType self,
    uint256 smartObjectId,
    address ephInvOwner,
    TransferItem[] memory items
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).ephemeralToInventoryTransfer(smartObjectId, ephInvOwner, items);
  }

  function setEphemeralToInventoryTransferAccess(
    InventoryInteractSystemType self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).setEphemeralToInventoryTransferAccess(
        smartObjectId,
        accessAddress,
        isAllowed
      );
  }

  function setInventoryToEphemeralTransferAccess(
    InventoryInteractSystemType self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).setInventoryToEphemeralTransferAccess(
        smartObjectId,
        accessAddress,
        isAllowed
      );
  }

  function setInventoryAdminAccess(
    InventoryInteractSystemType self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).setInventoryAdminAccess(smartObjectId, accessAddress, isAllowed);
  }

  function inventoryToEphemeralTransfer(
    InventoryInteractSystemType self,
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    TransferItem[] memory items
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).inventoryToEphemeralTransfer(
        smartObjectId,
        ephemeralInventoryOwner,
        items
      );
  }

  function ephemeralToInventoryTransfer(
    CallWrapper memory self,
    uint256 smartObjectId,
    address ephInvOwner,
    TransferItem[] memory items
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert InventoryInteractSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _ephemeralToInventoryTransfer_uint256_address_TransferItemArray.ephemeralToInventoryTransfer,
      (smartObjectId, ephInvOwner, items)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setEphemeralToInventoryTransferAccess(
    CallWrapper memory self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert InventoryInteractSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setEphemeralToInventoryTransferAccess_uint256_address_bool.setEphemeralToInventoryTransferAccess,
      (smartObjectId, accessAddress, isAllowed)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setInventoryToEphemeralTransferAccess(
    CallWrapper memory self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert InventoryInteractSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setInventoryToEphemeralTransferAccess_uint256_address_bool.setInventoryToEphemeralTransferAccess,
      (smartObjectId, accessAddress, isAllowed)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setInventoryAdminAccess(
    CallWrapper memory self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert InventoryInteractSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setInventoryAdminAccess_uint256_address_bool.setInventoryAdminAccess,
      (smartObjectId, accessAddress, isAllowed)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function inventoryToEphemeralTransfer(
    CallWrapper memory self,
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    TransferItem[] memory items
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert InventoryInteractSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _inventoryToEphemeralTransfer_uint256_address_TransferItemArray.inventoryToEphemeralTransfer,
      (smartObjectId, ephemeralInventoryOwner, items)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function ephemeralToInventoryTransfer(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    address ephInvOwner,
    TransferItem[] memory items
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _ephemeralToInventoryTransfer_uint256_address_TransferItemArray.ephemeralToInventoryTransfer,
      (smartObjectId, ephInvOwner, items)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setEphemeralToInventoryTransferAccess(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _setEphemeralToInventoryTransferAccess_uint256_address_bool.setEphemeralToInventoryTransferAccess,
      (smartObjectId, accessAddress, isAllowed)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setInventoryToEphemeralTransferAccess(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _setInventoryToEphemeralTransferAccess_uint256_address_bool.setInventoryToEphemeralTransferAccess,
      (smartObjectId, accessAddress, isAllowed)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setInventoryAdminAccess(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    address accessAddress,
    bool isAllowed
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _setInventoryAdminAccess_uint256_address_bool.setInventoryAdminAccess,
      (smartObjectId, accessAddress, isAllowed)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function inventoryToEphemeralTransfer(
    RootCallWrapper memory self,
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    TransferItem[] memory items
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _inventoryToEphemeralTransfer_uint256_address_TransferItemArray.inventoryToEphemeralTransfer,
      (smartObjectId, ephemeralInventoryOwner, items)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(InventoryInteractSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(InventoryInteractSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(
    InventoryInteractSystemType self,
    address from
  ) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(InventoryInteractSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(InventoryInteractSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (InventoryInteractSystemType) {
    return InventoryInteractSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(InventoryInteractSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _ephemeralToInventoryTransfer_uint256_address_TransferItemArray {
  function ephemeralToInventoryTransfer(
    uint256 smartObjectId,
    address ephInvOwner,
    TransferItem[] memory items
  ) external;
}

interface _setEphemeralToInventoryTransferAccess_uint256_address_bool {
  function setEphemeralToInventoryTransferAccess(uint256 smartObjectId, address accessAddress, bool isAllowed) external;
}

interface _setInventoryToEphemeralTransferAccess_uint256_address_bool {
  function setInventoryToEphemeralTransferAccess(uint256 smartObjectId, address accessAddress, bool isAllowed) external;
}

interface _setInventoryAdminAccess_uint256_address_bool {
  function setInventoryAdminAccess(uint256 smartObjectId, address accessAddress, bool isAllowed) external;
}

interface _inventoryToEphemeralTransfer_uint256_address_TransferItemArray {
  function inventoryToEphemeralTransfer(
    uint256 smartObjectId,
    address ephemeralInventoryOwner,
    TransferItem[] memory items
  ) external;
}

using InventoryInteractSystemLib for InventoryInteractSystemType global;
using InventoryInteractSystemLib for CallWrapper global;
using InventoryInteractSystemLib for RootCallWrapper global;
