[profile.default]
solc = "0.8.24"
evm_version="cancun"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 300
verbosity = 2
src = 'script'
out = 'out'
allow_paths = [
  "../mud-contracts/world-v2",
  "../mud-contracts/smart-object-framework-v2",
]

