// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";

/**
 * @title IEntitySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntitySystem {
  function evefrontier__registerClass(uint256 classId, ResourceId[] memory scopedSystemIds) external;

  function evefrontier__scopedRegisterClass(
    uint256 classId,
    address accessRoleMember,
    ResourceId[] memory scopedSystemIds
  ) external;

  function evefrontier__setClassAccessRole(uint256 classId, bytes32 newAccessRole) external;

  function evefrontier__deleteClass(uint256 classId) external;

  function evefrontier__deleteClasses(uint256[] memory classIds) external;

  function evefrontier__instantiate(uint256 classId, uint256 objectId, address accessRoleMember) external;

  function evefrontier__setObjectAccessRole(uint256 objectId, bytes32 newAccessRole) external;

  function evefrontier__deleteObject(uint256 objectId) external;

  function evefrontier__deleteObjects(uint256[] memory objectIds) external;
}
