// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRoleManagementSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRoleManagementSystem {
  function evefrontier__createRole(bytes32 role, bytes32 admin) external;

  function evefrontier__transferRoleAdmin(bytes32 role, bytes32 newAdmin) external;

  function evefrontier__grantRole(bytes32 role, address account) external;

  function evefrontier__revokeRole(bytes32 role, address account) external;

  function evefrontier__renounceRole(bytes32 role, address callerConfirmation) external;
}
