// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISOFAccessSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISOFAccessSystem {
  function sofaccess__allowClassAccessRole(uint256 classId, bytes memory targetCallData) external view;

  function sofaccess__allowClassScopedSystemOrDirectClassAccessRole(
    uint256 entityId,
    bytes memory targetCallData
  ) external view;

  function sofaccess__allowClassScopedSystemOrDirectObjectAccessRole(
    uint256 objectId,
    bytes memory targetCallData
  ) external view;

  function sofaccess__allowEntitySystemOrDirectAccessRole(uint256 entityId, bytes memory targetCallData) external view;
}
