// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Id } from "../../libs/Id.sol";

/**
 * @title ISOFAccessSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISOFAccessSystem {
  function sofaccess__allowClassAccessRole(Id classId, bytes memory targetCallData) external view;

  function sofaccess__allowClassScopedSystemOrDirectClassAccessRole(
    Id entityId,
    bytes memory targetCallData
  ) external view;

  function sofaccess__allowClassScopedSystemOrDirectObjectAccessRole(
    Id objectId,
    bytes memory targetCallData
  ) external view;

  function sofaccess__allowEntitySystemOrDirectAccessRole(Id entityId, bytes memory targetCallData) external view;
}
