// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TagParams } from "../../namespaces/evefrontier/systems/tag-system/types.sol";
import { TagId } from "../../libs/TagId.sol";

/**
 * @title ITagSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITagSystem {
  function evefrontier__setTag(uint256 entityId, TagParams memory tagParams) external;

  function evefrontier__setTags(uint256 entityId, TagParams[] memory tagParams) external;

  function evefrontier__removeTag(uint256 entityId, TagId tagId) external;

  function evefrontier__removeTags(uint256 entityId, TagId[] memory tagIds) external;
}
