// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SmartAssembly, SmartAssemblyData } from "./tables/SmartAssembly.sol";
import { EntityRecord, EntityRecordData } from "./tables/EntityRecord.sol";
import { EntityRecordMeta, EntityRecordMetaData } from "./tables/EntityRecordMeta.sol";
import { StaticData } from "./tables/StaticData.sol";
import { StaticDataMetada } from "./tables/StaticDataMetada.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { CharacterToken } from "./tables/CharacterToken.sol";
import { CharactersByAddr } from "./tables/CharactersByAddr.sol";
import { Balances } from "./tables/Balances.sol";
import { ERC721Metadata, ERC721MetadataData } from "./tables/ERC721Metadata.sol";
import { TokenURI } from "./tables/TokenURI.sol";
import { Owners } from "./tables/Owners.sol";
import { TokenApproval } from "./tables/TokenApproval.sol";
import { OperatorApproval } from "./tables/OperatorApproval.sol";
import { ERC721Registry } from "./tables/ERC721Registry.sol";
import { Location, LocationData } from "./tables/Location.sol";
import { GlobalDeployable, GlobalDeployableData } from "./tables/GlobalDeployable.sol";
import { DeployableState, DeployableStateData } from "./tables/DeployableState.sol";
import { DeployableToken } from "./tables/DeployableToken.sol";
import { Fuel, FuelData } from "./tables/Fuel.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
import { InventoryItem, InventoryItemData } from "./tables/InventoryItem.sol";
import { EphemeralInvCapa } from "./tables/EphemeralInvCapa.sol";
import { EphemeralInv, EphemeralInvData } from "./tables/EphemeralInv.sol";
import { EphemeralInvItem, EphemeralInvItemData } from "./tables/EphemeralInvItem.sol";
import { ItemTransferOffc, ItemTransferOffcData } from "./tables/ItemTransferOffc.sol";
import { SmartTurretConfi } from "./tables/SmartTurretConfi.sol";
import { SmartGateConfig, SmartGateConfigData } from "./tables/SmartGateConfig.sol";
import { SmartGateLink, SmartGateLinkData } from "./tables/SmartGateLink.sol";
