// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAccessSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAccessSystem {
  error Access_NotAdmin(address caller);
  error Access_NotOwner(address caller, uint256 objectId);
  error Access_NotAdminOrOwner(address caller, uint256 objectId);

  function evefrontier__onlyDeployableOwner(uint256 objectId, bytes memory data) external view;

  function evefrontier__onlyAdmin(uint256 objectId, bytes memory data) external view;

  function evefrontier__onlyAdminOrDeployableOwner(uint256 objectId, bytes memory data) external view;

  function evefrontier__isAdmin(address caller) external view returns (bool);

  function evefrontier__isOwner(address caller, uint256 objectId) external view returns (bool);
}
