// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { State } from "../common.sol";
import { EntityRecordData } from "../../namespaces/evefrontier/systems/entity-record/types.sol";
import { SmartObjectData } from "../../namespaces/evefrontier/systems/deployable/types.sol";
import { WorldPosition } from "../../namespaces/evefrontier/systems/location/types.sol";

/**
 * @title ICrudeLiftSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICrudeLiftSystem {
  error LensNotInserted();
  error LensExhausted();
  error LensAlreadyInserted();
  error LensExpired();
  error CannotRemoveLensWhileMining();
  error AlreadyMining();
  error NotMining();
  error RiftNotFoundOrDepleted();
  error InsufficientCrude();
  error RiftCollapsed();
  error CrudeLiftWrongState(uint256 crudeLiftId, State currentState);

  function evefrontier__createAndAnchorCrudeLift(
    uint256 smartObjectId,
    EntityRecordData memory entityRecordData,
    SmartObjectData memory smartObjectData,
    WorldPosition memory worldPosition,
    uint256 fuelUnitVolume,
    uint256 fuelConsumptionIntervalInSeconds,
    uint256 fuelMaxCapacity,
    uint256 storageCapacity,
    uint256 ephemeralStorageCapacity
  ) external;

  function evefrontier__insertLens(uint256 crudeLiftId) external;

  function evefrontier__startMining(uint256 crudeLiftId, uint256 riftId, uint256 miningRate) external;

  function evefrontier__stopMining(uint256 crudeLiftId) external;

  function evefrontier__removeLens(uint256 smartObjectId, address receiver) external;

  function evefrontier__addCrude(uint256 smartObjectId, uint256 amount) external;

  function evefrontier__removeCrude(uint256 smartObjectId, uint256 amount) external;

  function evefrontier__clearCrude(uint256 smartObjectId) external;

  function evefrontier__getCrudeAmount(uint256 smartObjectId) external view returns (uint256);
}
