// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IERC20System
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IERC20System {
  function evefrontier__name() external view returns (string memory);

  function evefrontier__symbol() external view returns (string memory);

  function evefrontier__decimals() external view returns (uint8);

  function evefrontier__totalSupply() external view returns (uint256);

  function evefrontier__balanceOf(address account) external view returns (uint256);

  function evefrontier__allowance(address owner, address spender) external view returns (uint256);

  function evefrontier__transfer(address to, uint256 value) external returns (bool);

  function evefrontier__approve(address spender, uint256 value) external returns (bool);

  function evefrontier__transferFrom(address from, address to, uint256 value) external returns (bool);

  function evefrontier__mint(address account, uint256 value) external;

  function evefrontier__burn(address account, uint256 value) external;
}
