// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IERC721System
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IERC721System {
  function null__balanceOf(address owner) external view returns (uint256);

  function null__ownerOf(uint256 tokenId) external view returns (address);

  function null__name() external view returns (string memory);

  function null__symbol() external view returns (string memory);

  function null__tokenURI(uint256 tokenId) external view returns (string memory);

  function null__approve(address to, uint256 tokenId) external;

  function null__getApproved(uint256 tokenId) external view returns (address);

  function null__setApprovalForAll(address operator, bool approved) external;

  function null__isApprovedForAll(address owner, address operator) external view returns (bool);

  function null__transferFrom(address from, address to, uint256 tokenId) external;

  function null__safeTransferFrom(address from, address to, uint256 tokenId) external;

  function null__safeTransferFrom(address from, address to, uint256 tokenId, bytes memory data) external;

  function null__mint(address to, uint256 tokenId) external;

  function null__safeMint(address to, uint256 tokenId) external;

  function null__safeMint(address to, uint256 tokenId, bytes memory data) external;

  function null__burn(uint256 tokenId) external;
}
