// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SOFAccessSystem } from "../../systems/sof-access-system/SOFAccessSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type SOFAccessSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "sofaccess", name: "SOFAccessSystem" }))
SOFAccessSystemType constant sOFAccessSystem = SOFAccessSystemType.wrap(
  0x7379736f666163636573730000000000534f4641636365737353797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title SOFAccessSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library SOFAccessSystemLib {
  error SOFAccessSystemLib_CallingFromRootSystem();

  function allowClassAccessRole(SOFAccessSystemType self, uint256 classId, bytes memory targetCallData) internal view {
    return CallWrapper(self.toResourceId(), address(0)).allowClassAccessRole(classId, targetCallData);
  }

  function allowClassScopedSystemOrDirectClassAccessRole(
    SOFAccessSystemType self,
    uint256 entityId,
    bytes memory targetCallData
  ) internal view {
    return
      CallWrapper(self.toResourceId(), address(0)).allowClassScopedSystemOrDirectClassAccessRole(
        entityId,
        targetCallData
      );
  }

  function allowClassScopedSystemOrDirectObjectAccessRole(
    SOFAccessSystemType self,
    uint256 objectId,
    bytes memory targetCallData
  ) internal view {
    return
      CallWrapper(self.toResourceId(), address(0)).allowClassScopedSystemOrDirectObjectAccessRole(
        objectId,
        targetCallData
      );
  }

  function allowEntitySystemOrDirectAccessRole(
    SOFAccessSystemType self,
    uint256 entityId,
    bytes memory targetCallData
  ) internal view {
    return CallWrapper(self.toResourceId(), address(0)).allowEntitySystemOrDirectAccessRole(entityId, targetCallData);
  }

  function allowClassAccessRole(CallWrapper memory self, uint256 classId, bytes memory targetCallData) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert SOFAccessSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _allowClassAccessRole_uint256_bytes.allowClassAccessRole,
      (classId, targetCallData)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function allowClassScopedSystemOrDirectClassAccessRole(
    CallWrapper memory self,
    uint256 entityId,
    bytes memory targetCallData
  ) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert SOFAccessSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _allowClassScopedSystemOrDirectClassAccessRole_uint256_bytes.allowClassScopedSystemOrDirectClassAccessRole,
      (entityId, targetCallData)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function allowClassScopedSystemOrDirectObjectAccessRole(
    CallWrapper memory self,
    uint256 objectId,
    bytes memory targetCallData
  ) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert SOFAccessSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _allowClassScopedSystemOrDirectObjectAccessRole_uint256_bytes.allowClassScopedSystemOrDirectObjectAccessRole,
      (objectId, targetCallData)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function allowEntitySystemOrDirectAccessRole(
    CallWrapper memory self,
    uint256 entityId,
    bytes memory targetCallData
  ) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert SOFAccessSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _allowEntitySystemOrDirectAccessRole_uint256_bytes.allowEntitySystemOrDirectAccessRole,
      (entityId, targetCallData)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function allowClassAccessRole(
    RootCallWrapper memory self,
    uint256 classId,
    bytes memory targetCallData
  ) internal view {
    bytes memory systemCall = abi.encodeCall(
      _allowClassAccessRole_uint256_bytes.allowClassAccessRole,
      (classId, targetCallData)
    );
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function allowClassScopedSystemOrDirectClassAccessRole(
    RootCallWrapper memory self,
    uint256 entityId,
    bytes memory targetCallData
  ) internal view {
    bytes memory systemCall = abi.encodeCall(
      _allowClassScopedSystemOrDirectClassAccessRole_uint256_bytes.allowClassScopedSystemOrDirectClassAccessRole,
      (entityId, targetCallData)
    );
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function allowClassScopedSystemOrDirectObjectAccessRole(
    RootCallWrapper memory self,
    uint256 objectId,
    bytes memory targetCallData
  ) internal view {
    bytes memory systemCall = abi.encodeCall(
      _allowClassScopedSystemOrDirectObjectAccessRole_uint256_bytes.allowClassScopedSystemOrDirectObjectAccessRole,
      (objectId, targetCallData)
    );
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function allowEntitySystemOrDirectAccessRole(
    RootCallWrapper memory self,
    uint256 entityId,
    bytes memory targetCallData
  ) internal view {
    bytes memory systemCall = abi.encodeCall(
      _allowEntitySystemOrDirectAccessRole_uint256_bytes.allowEntitySystemOrDirectAccessRole,
      (entityId, targetCallData)
    );
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function callFrom(SOFAccessSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(SOFAccessSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(SOFAccessSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(SOFAccessSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(SOFAccessSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (SOFAccessSystemType) {
    return SOFAccessSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(SOFAccessSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _allowClassAccessRole_uint256_bytes {
  function allowClassAccessRole(uint256 classId, bytes memory targetCallData) external;
}

interface _allowClassScopedSystemOrDirectClassAccessRole_uint256_bytes {
  function allowClassScopedSystemOrDirectClassAccessRole(uint256 entityId, bytes memory targetCallData) external;
}

interface _allowClassScopedSystemOrDirectObjectAccessRole_uint256_bytes {
  function allowClassScopedSystemOrDirectObjectAccessRole(uint256 objectId, bytes memory targetCallData) external;
}

interface _allowEntitySystemOrDirectAccessRole_uint256_bytes {
  function allowEntitySystemOrDirectAccessRole(uint256 entityId, bytes memory targetCallData) external;
}

using SOFAccessSystemLib for SOFAccessSystemType global;
using SOFAccessSystemLib for CallWrapper global;
using SOFAccessSystemLib for RootCallWrapper global;
