// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SmartAssembly, SmartAssemblyData } from "./tables/SmartAssembly.sol";
import { EntityRecord, EntityRecordData } from "./tables/EntityRecord.sol";
import { EntityRecordMetadata, EntityRecordMetadataData } from "./tables/EntityRecordMetadata.sol";
import { StaticData } from "./tables/StaticData.sol";
import { StaticDataMetadata } from "./tables/StaticDataMetadata.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { CharacterToken } from "./tables/CharacterToken.sol";
import { CharactersByAddress } from "./tables/CharactersByAddress.sol";
import { Balances } from "./tables/Balances.sol";
import { ERC721Metadata, ERC721MetadataData } from "./tables/ERC721Metadata.sol";
import { TokenURI } from "./tables/TokenURI.sol";
import { Owners } from "./tables/Owners.sol";
import { TokenApproval } from "./tables/TokenApproval.sol";
import { OperatorApproval } from "./tables/OperatorApproval.sol";
import { ERC721Registry } from "./tables/ERC721Registry.sol";
import { ERC20Metadata, ERC20MetadataData } from "./tables/ERC20Metadata.sol";
import { Allowances } from "./tables/Allowances.sol";
import { TotalSupply } from "./tables/TotalSupply.sol";
import { ERC20Registry } from "./tables/ERC20Registry.sol";
import { Location, LocationData } from "./tables/Location.sol";
import { GlobalDeployableState, GlobalDeployableStateData } from "./tables/GlobalDeployableState.sol";
import { DeployableState, DeployableStateData } from "./tables/DeployableState.sol";
import { DeployableToken } from "./tables/DeployableToken.sol";
import { Fuel, FuelData } from "./tables/Fuel.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
import { InventoryItem, InventoryItemData } from "./tables/InventoryItem.sol";
import { EphemeralInvCapacity } from "./tables/EphemeralInvCapacity.sol";
import { EphemeralInv, EphemeralInvData } from "./tables/EphemeralInv.sol";
import { EphemeralInvItem, EphemeralInvItemData } from "./tables/EphemeralInvItem.sol";
import { ItemTransferOffchain, ItemTransferOffchainData } from "./tables/ItemTransferOffchain.sol";
import { SmartTurretConfig } from "./tables/SmartTurretConfig.sol";
import { SmartGateConfig, SmartGateConfigData } from "./tables/SmartGateConfig.sol";
import { SmartGateLink, SmartGateLinkData } from "./tables/SmartGateLink.sol";
import { CrudeLift, CrudeLiftData } from "./tables/CrudeLift.sol";
import { CrudeOwned } from "./tables/CrudeOwned.sol";
import { Lens, LensData } from "./tables/Lens.sol";
import { Rift, RiftData } from "./tables/Rift.sol";
