// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { AdminAccessSystem } from "../../systems/access-systems/AdminAccessSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type AdminAccessSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "evefrontier", name: "AdminAccessSyste" }))
AdminAccessSystemType constant adminAccessSystem = AdminAccessSystemType.wrap(
  0x737965766566726f6e7469657200000041646d696e4163636573735379737465
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title AdminAccessSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library AdminAccessSystemLib {
  error AdminAccessSystemLib_CallingFromRootSystem();
  error AdminAccess_NotAdmin(address caller);

  function onlyAdmin(AdminAccessSystemType self, uint256 objectId, bytes memory data) internal view {
    return CallWrapper(self.toResourceId(), address(0)).onlyAdmin(objectId, data);
  }

  function onlyAdmin(CallWrapper memory self, uint256 objectId, bytes memory data) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert AdminAccessSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_onlyAdmin_uint256_bytes.onlyAdmin, (objectId, data));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function onlyAdmin(RootCallWrapper memory self, uint256 objectId, bytes memory data) internal view {
    bytes memory systemCall = abi.encodeCall(_onlyAdmin_uint256_bytes.onlyAdmin, (objectId, data));
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function callFrom(AdminAccessSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(AdminAccessSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(AdminAccessSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(AdminAccessSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(AdminAccessSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (AdminAccessSystemType) {
    return AdminAccessSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(AdminAccessSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _onlyAdmin_uint256_bytes {
  function onlyAdmin(uint256 objectId, bytes memory data) external;
}

using AdminAccessSystemLib for AdminAccessSystemType global;
using AdminAccessSystemLib for CallWrapper global;
using AdminAccessSystemLib for RootCallWrapper global;
