// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LocationSystem } from "../../systems/location/LocationSystem.sol";
import { LocationData } from "../index.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type LocationSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "evefrontier", name: "LocationSystem" }))
LocationSystemType constant locationSystem = LocationSystemType.wrap(
  0x737965766566726f6e746965720000004c6f636174696f6e53797374656d0000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title LocationSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library LocationSystemLib {
  error LocationSystemLib_CallingFromRootSystem();

  function saveLocation(LocationSystemType self, uint256 smartObjectId, LocationData memory locationData) internal {
    return CallWrapper(self.toResourceId(), address(0)).saveLocation(smartObjectId, locationData);
  }

  function setSolarSystemId(LocationSystemType self, uint256 smartObjectId, uint256 solarSystemId) internal {
    return CallWrapper(self.toResourceId(), address(0)).setSolarSystemId(smartObjectId, solarSystemId);
  }

  function setX(LocationSystemType self, uint256 smartObjectId, uint256 x) internal {
    return CallWrapper(self.toResourceId(), address(0)).setX(smartObjectId, x);
  }

  function setY(LocationSystemType self, uint256 smartObjectId, uint256 y) internal {
    return CallWrapper(self.toResourceId(), address(0)).setY(smartObjectId, y);
  }

  function setZ(LocationSystemType self, uint256 smartObjectId, uint256 z) internal {
    return CallWrapper(self.toResourceId(), address(0)).setZ(smartObjectId, z);
  }

  function saveLocation(CallWrapper memory self, uint256 smartObjectId, LocationData memory locationData) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert LocationSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _saveLocation_uint256_LocationData.saveLocation,
      (smartObjectId, locationData)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setSolarSystemId(CallWrapper memory self, uint256 smartObjectId, uint256 solarSystemId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert LocationSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setSolarSystemId_uint256_uint256.setSolarSystemId,
      (smartObjectId, solarSystemId)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setX(CallWrapper memory self, uint256 smartObjectId, uint256 x) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert LocationSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setX_uint256_uint256.setX, (smartObjectId, x));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setY(CallWrapper memory self, uint256 smartObjectId, uint256 y) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert LocationSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setY_uint256_uint256.setY, (smartObjectId, y));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setZ(CallWrapper memory self, uint256 smartObjectId, uint256 z) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert LocationSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setZ_uint256_uint256.setZ, (smartObjectId, z));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function saveLocation(RootCallWrapper memory self, uint256 smartObjectId, LocationData memory locationData) internal {
    bytes memory systemCall = abi.encodeCall(
      _saveLocation_uint256_LocationData.saveLocation,
      (smartObjectId, locationData)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setSolarSystemId(RootCallWrapper memory self, uint256 smartObjectId, uint256 solarSystemId) internal {
    bytes memory systemCall = abi.encodeCall(
      _setSolarSystemId_uint256_uint256.setSolarSystemId,
      (smartObjectId, solarSystemId)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setX(RootCallWrapper memory self, uint256 smartObjectId, uint256 x) internal {
    bytes memory systemCall = abi.encodeCall(_setX_uint256_uint256.setX, (smartObjectId, x));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setY(RootCallWrapper memory self, uint256 smartObjectId, uint256 y) internal {
    bytes memory systemCall = abi.encodeCall(_setY_uint256_uint256.setY, (smartObjectId, y));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setZ(RootCallWrapper memory self, uint256 smartObjectId, uint256 z) internal {
    bytes memory systemCall = abi.encodeCall(_setZ_uint256_uint256.setZ, (smartObjectId, z));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(LocationSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(LocationSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(LocationSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(LocationSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(LocationSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (LocationSystemType) {
    return LocationSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(LocationSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _saveLocation_uint256_LocationData {
  function saveLocation(uint256 smartObjectId, LocationData memory locationData) external;
}

interface _setSolarSystemId_uint256_uint256 {
  function setSolarSystemId(uint256 smartObjectId, uint256 solarSystemId) external;
}

interface _setX_uint256_uint256 {
  function setX(uint256 smartObjectId, uint256 x) external;
}

interface _setY_uint256_uint256 {
  function setY(uint256 smartObjectId, uint256 y) external;
}

interface _setZ_uint256_uint256 {
  function setZ(uint256 smartObjectId, uint256 z) external;
}

using LocationSystemLib for LocationSystemType global;
using LocationSystemLib for CallWrapper global;
using LocationSystemLib for RootCallWrapper global;
