name: Build
description: Builds the monorepo based on changes

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 8.11.x

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Cache Nx cache directory
      uses: actions/cache@v2
      with:
        path: ~/.nx
        key: ${{ runner.os }}-nx-${{ hashFiles('**/nx.json') }}

    - name: Cache codegen directory
      uses: actions/cache@v2
      with:
        path: ./**/src/codegen
        key: ${{ runner.os }}-codegen-${{ hashFiles('./**/**/src/codegen/**') }}

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install packages
      shell: bash
      run: |
        pnpm install

    - name: Build feature branch
      if: github.ref_name != 'develop' #only build on feature branches
      shell: bash
      run: |
        MAIN_HEAD=$(git rev-parse origin/main)
        pnpm nx affected -t build --base=$MAIN_HEAD --verbose

    - name: Build on DEVELOP
      shell: bash
      if: github.ref_name == 'develop' #only build on default branch
      run: |
        git show-ref
        THE_COMMIT_BEFORE_THIS_ONE=$(git rev-parse HEAD~1)
        echo "rev-parse head~1: " $THE_COMMIT_BEFORE_THIS_ONE
        pnpm nx affected -t build --base=$THE_COMMIT_BEFORE_THIS_ONE --verbose

    - name: Lint on feature branch
      shell: bash
      if: github.ref_name != 'develop' #only build on feature branches
      run: |
        MAIN_HEAD=$(git rev-parse origin/main)
        pnpm nx affected -t lint --base=$MAIN_HEAD --verbose

    - name: Lint project on DEVELOP
      shell: bash
      if: github.ref_name == 'develop' #only build on main branch
      run: |
        git show-ref
        THE_COMMIT_BEFORE_THIS_ONE=$(git rev-parse HEAD~1)
        echo "rev-parse head~1: " $THE_COMMIT_BEFORE_THIS_ONE
        pnpm nx affected -t lint --base=$THE_COMMIT_BEFORE_THIS_ONE --verbose
