// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { AccessConfig, AccessConfigData } from "./tables/AccessConfig.sol";
import { Role, RoleData } from "./tables/Role.sol";
import { HasRole } from "./tables/HasRole.sol";
import { Classes, ClassesData } from "./tables/Classes.sol";
import { ClassSystemTagMap, ClassSystemTagMapData } from "./tables/ClassSystemTagMap.sol";
import { ClassObjectMap, ClassObjectMapData } from "./tables/ClassObjectMap.sol";
import { Objects, ObjectsData } from "./tables/Objects.sol";
import { ObjectSystemTagMap, ObjectSystemTagMapData } from "./tables/ObjectSystemTagMap.sol";
import { SystemTags, SystemTagsData } from "./tables/SystemTags.sol";
